Project: Newsweek
OlukaDenis/News-Week pull request #9
Opened 2019-10-18 01:09 UTC by OlukaDenis

- Use of bootstrap class
- Responsivity
- Three break points

2019-10-18 19:53 UTC, wathigo requested changes
### Hi @OlukaDenis  :wave:  
I like the effort you have put into this project.
Let's fix a couple of things before we mark this as complete.

**[REQUIRED]**
* We have a problem at a screen width of `600px`. The **Top Stories** heading is not visible. See :point_down:  
![Screenshot from 2019-10-18 15-17-10](https://user-images.githubusercontent.com/44072711/67123165-855ba700-f1bd-11e9-9ee7-eec1d7447928.png)

* On the smaller screens a hamburger icon appears on the navigation bar.
* At a screen size of around `500px`. The sub-nav is displayed and we have a big margin on the right. The sub-nav should not displayed. Let's fix this :point_down: 
![Screenshot from 2019-10-18 15-51-16](https://user-images.githubusercontent.com/44072711/67123735-2ac34a80-f1bf-11e9-92c3-e7e6eed2f96d.png)

* Reduce the margin on the left and right of the `footer` element to look more like the original page on the smaller screens.
* Fix the issues pointed out in the comments below :point_down:  

After implementing the changes, submit another request for review.

_Happy Coding :computer: 
Reviewed by: **Simon Wathigo**_

2019-10-18 19:53 UTC, wathigo commented on index.html
> +            <a class="text-decoration-none px-2 pt-2" style="background: white; color:#f72210; " href="#">Subscribe <i
**[REQUIRED]** Remove inline styles. Add all your styles to the external CSS file.

2019-10-18 19:53 UTC, wathigo commented on index.html
> +              <span class="navbar-toggler-icon pt-2" style="color: white;"></span>
**[REQUIRED]** Remove inline styles. Add all your styles to the external CSS file.

2019-10-18 19:53 UTC, wathigo commented on index.html
> +              <ul class="style navbar-nav float-right  mt-3" style="margin-right: -1em; background: white;">
**[REQUIRED]** Remove inline styles. Add all your styles to the external CSS file.

2019-10-18 19:53 UTC, wathigo commented on index.html
> +    <div class="container-fluid  d-lg-block d-md-none d-sm-none " style="background-color: rgba(244, 245, 246, 0.973);">
**[REQUIRED]** Remove inline styles. Add all your styles to the external CSS file.

2019-10-18 19:53 UTC, wathigo commented on index.html
> +            <a class=" text-decoration-none font-weight-bolder p-1" style=" background: white; color:rgb(247,34,16)"
**[REQUIRED]** Remove inline styles. Add all your styles to the external CSS file.

2019-10-22 01:06 UTC, Redvanisation approved these changes
### Hello @OlukaDenis  🌟 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

2019-10-22 07:11 UTC, merged